In [1]:
import numpy as np
# creaiting and reshaping matrix.
matrix = np.array(range(1, 11)).reshape(2, 5)

print(matrix)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
import numpy as np
#Creating and extracting metrix
array = np.array(range(1, 21))
subset = array[5:15]

print(subset)




[ 6  7  8  9 10 11 12 13 14 15]


In [5]:
import pandas as pd
# Create panda series
fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

# Adding new item
fruits['pears'] = 4

print(fruits)



apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [7]:
import pandas as pd
#Data input
data = {
    'name': ['Alice', 'Boby', 'Charly', 'David', 'George', 'Fransis', 'Grace', 'shiny', 'jinu', 'Jackson'],
    'age': [25, 30, 22, 35, 28, 40, 32, 29, 24, 27],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male']
}
df = pd.DataFrame(data)

print(df)



      name  age  gender
0    Alice   25  Female
1     Boby   30    Male
2   Charly   22    Male
3    David   35    Male
4   George   28    Male
5  Fransis   40    Male
6    Grace   32  Female
7    shiny   29  Female
8     jinu   24    Male
9  Jackson   27    Male


In [9]:
import pandas as pd
#Creating datas
df = pd.DataFrame({
    'name': ['Alice', 'Boby', 'Charly', 'David', 'George', 'Fransis', 'Grace', 'shiny', 'jinu', 'Jackson'],
    'age': [25, 30, 22, 35, 28, 40, 32, 29, 24, 27],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male']
})
# Adding new column
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']

print(df)


      name  age  gender  occupation
0    Alice   25  Female  Programmer
1     Boby   30    Male     Manager
2   Charly   22    Male     Analyst
3    David   35    Male  Programmer
4   George   28    Male     Manager
5  Fransis   40    Male     Analyst
6    Grace   32  Female  Programmer
7    shiny   29  Female     Manager
8     jinu   24    Male     Analyst
9  Jackson   27    Male  Programmer


In [11]:
import pandas as pd
# Creating datas
df = pd.DataFrame({
    'name': ['Alice', 'Boby', 'Charly', 'David', 'George', 'Fransis', 'Grace', 'shiny', 'jinu', 'Jackson'],
    'age': [25, 30, 22, 35, 28, 40, 32, 29, 24, 27],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male'],
    'occupation': ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
})
# Select age is >= 30
filtered_df = df[df['age'] >= 30]

print(filtered_df)


      name  age  gender  occupation
1     Boby   30    Male     Manager
3    David   35    Male  Programmer
5  Fransis   40    Male     Analyst
6    Grace   32  Female  Programmer


In [13]:
import pandas as pd
# Create the DataFrame
df = pd.DataFrame({
    'name': ['Alice', 'Boby', 'Charly', 'David', 'George', 'Fransis', 'Grace', 'shiny', 'jinu', 'Jackson'],
    'age': [25, 30, 22, 35, 28, 40, 32, 29, 24, 27],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male'],
    'occupation': ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
})

# Save the data to CSV file
df.to_csv('data.csv', index=False)
# Read the CSV file
df_from_csv = pd.read_csv('data.csv')
# Display the CSV file
print(df_from_csv)


      name  age  gender  occupation
0    Alice   25  Female  Programmer
1     Boby   30    Male     Manager
2   Charly   22    Male     Analyst
3    David   35    Male  Programmer
4   George   28    Male     Manager
5  Fransis   40    Male     Analyst
6    Grace   32  Female  Programmer
7    shiny   29  Female     Manager
8     jinu   24    Male     Analyst
9  Jackson   27    Male  Programmer
